/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-06-02 08:54:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\"  href=\"../styles/global.css\">\r\n");
      out.write("    <link rel=\"stylesheet\"  href=\"../styles/css/header.styles.css\">\r\n");
      out.write("    <link rel=\"stylesheet\"  href=\"../styles/css/carousel.styles.css\">\r\n");
      out.write("\r\n");
      out.write("    <title>About Us</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("    * {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Global Styles */\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Header */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .nav-links li {\r\n");
      out.write("        margin-right: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-links a {\r\n");
      out.write("        color: rgb(0, 0, 0);\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-links a:hover {\r\n");
      out.write("        background-color: #ffa846;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* About Section */\r\n");
      out.write("\r\n");
      out.write("    .about {\r\n");
      out.write("        background: #ffffff;\r\n");
      out.write("\r\n");
      out.write("        /*\r\n");
      out.write("                background: linear-gradient(360deg, rgb(245, 255, 245) 0%, #ffa846 100%);*/\r\n");
      out.write("        /* padding: 100px 0 20px 0;*/\r\n");
      out.write("        text-align: center;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .about h1 {\r\n");
      out.write("        font-size: 4rem;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        color:#ffffff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .about p {\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        color: #323030;\r\n");
      out.write("        max-width: 1000px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .about-info {\r\n");
      out.write("        margin: 2rem 2rem;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .about-img {\r\n");
      out.write("        width: 20rem;\r\n");
      out.write("        height: 20rem;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .about-img img {\r\n");
      out.write("        width: 120%;\r\n");
      out.write("        height: 120%;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        object-fit: cover;\r\n");
      out.write("        padding-right: 50px;\r\n");
      out.write("        padding-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .about-info p {\r\n");
      out.write("        font-size: 1.3rem;\r\n");
      out.write("        margin: 0 2rem;\r\n");
      out.write("        text-align: justify;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    button {\r\n");
      out.write("        border: none;\r\n");
      out.write("        outline: 0;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        margin: 2rem;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        color: white;\r\n");
      out.write("        background-color: #ffa846;;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        width: 15rem;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    button:hover {\r\n");
      out.write("        background-color: #ffa846;;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Team Section */\r\n");
      out.write("\r\n");
      out.write("    .team {\r\n");
      out.write("        padding: 30px 0;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .team h1 {\r\n");
      out.write("        font-size: 2.5rem;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .team-cards {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        gap: 15px;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card {\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        border-radius: 6px;\r\n");
      out.write("        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.5);\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        transition: transform 0.2s, box-shadow 0.2s;\r\n");
      out.write("        width: 18rem;\r\n");
      out.write("        height: 25rem;\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card:hover {\r\n");
      out.write("        transform: translateY(-5px);\r\n");
      out.write("        box-shadow: 0 8px 5px rgba(0, 0, 0, 0.5);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-img {\r\n");
      out.write("        width: 18rem;\r\n");
      out.write("        height: 12rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-img img {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        object-fit: cover;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-info .button {\r\n");
      out.write("        background-color: #ffa846;\r\n");
      out.write("        color: white;\r\n");
      out.write("        border: none;\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: background-color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-info .button:hover {\r\n");
      out.write("        background-color: #ff8c00;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-name {\r\n");
      out.write("        font-size: 1.5rem;\r\n");
      out.write("        margin: 10px 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-role {\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        color: #888;\r\n");
      out.write("        margin: 5px 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-email {\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        color: #555;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Footer */\r\n");
      out.write("    footer {\r\n");
      out.write("        background-color: #222;\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 20px 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        nav {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .nav-links li {\r\n");
      out.write("            margin-right: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about h1 {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about p {\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-info {\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-info p {\r\n");
      out.write("            margin: 1rem 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-info button {\r\n");
      out.write("            margin: 1rem 2rem;\r\n");
      out.write("            width: 10rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .team {\r\n");
      out.write("            margin: 0 1rem;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<section style=\"position: relative;\">\r\n");
      out.write("    <div class=\"carousel-item active c-item\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/gadgetsone.jpg\" class=\"d-block w-100 c-img\" alt=\"Slide 1\">\r\n");
      out.write("        <div class=\"carousel-caption top-0 mt-4\">\r\n");
      out.write("            <p class=\"mt-5 fs-3 text-uppercase\"></p>\r\n");
      out.write("            <h1 class=\"display-1 fw-bolder text-capitalize\">About Us</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("<section>\r\n");
      out.write("    <div class=\"text-container\">\r\n");
      out.write("        <p style=\"font-weight: bold; color: #ff8c00; text-align: center;\">.GADGET is a leading platform........</p>\r\n");
      out.write("        <p style=\"text-align: center\">We work on UI/UX and functionality as well, so that a plugin comes with proper structure and stunning looks that suit your web app and website. We take a small toolkit here and ride it well so that it is fit for your use. One who performs well and looks even better. Here, we are trying to give you all kinds of technical content, whether it is related to designing or functionality. We are creating content in a lot of languages and will continue to make it free of charge even if you use it without any problem. Which is a very important thing. Here you can also share the content you create; if our technical team likes it, then we will also share it on our blog. In the end, I would say to keep visiting our website and enjoy the quality content.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"team\">\r\n");
      out.write("    <h1>Meet Our Team</h1>\r\n");
      out.write("    <div class=\"team-cards\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Cards here -->\r\n");
      out.write("        <!-- Card 1 -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-img\">\r\n");
      out.write("                <img\r\n");
      out.write("                        src=\"../assets/Sushil.jpg\" alt=\"User 1\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-info\">\r\n");
      out.write("                <h2 class=\"card-name\">Sushil Dawadi</h2>\r\n");
      out.write("                <p class=\"card-role\"> Founder</p>\r\n");
      out.write("                <p class=\"card-email\">sushildawadi14@gmail.com</p>\r\n");
      out.write("                <p><button class=\"button\" onclick=\"window.open( 'https://www.facebook.com/SushilDawadi07', '_blank')\">Contact</button></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Card 2 -->\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-img\">\r\n");
      out.write("                <img\r\n");
      out.write("                        src=\"../assets/sachin.jpg\" alt=\"User 3\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-info\">\r\n");
      out.write("                <h2 class=\"card-name\">Sachin Sapkota</h2>\r\n");
      out.write("                <p class=\"card-role\">Founder</p>\r\n");
      out.write("                <p class=\"card-email\">sacheensapkota10@gmail.com</p>\r\n");
      out.write("                <p><button class=\"button\" onclick=\"window.open('https://www.facebook.com/sapkota.sacheen', '_blank')\">Contact</button></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Card 3 -->\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-img\">\r\n");
      out.write("                <img\r\n");
      out.write("                        src=\"../assets/abishkar.jpg\" alt=\"User 2\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-info\">\r\n");
      out.write("                <h2 class=\"card-name\">Abishkar Chapagain</h2>\r\n");
      out.write("                <p class=\"card-role\">Founder</p>\r\n");
      out.write("                <p class=\"card-email\">abishkarchapagain1@gmail.com</p>\r\n");
      out.write("                <p><button class=\"button\" onclick=\"window.open('https://www.facebook.com/abishkar.chapagain', '_blank')\">Contact</button></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- card 4 -->\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-img\">\r\n");
      out.write("                <img\r\n");
      out.write("                        src=\"../assets/Manish.jpg\" alt=\"User 3\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-info\">\r\n");
      out.write("                <h2 class=\"card-name\">Manish Dhamala</h2>\r\n");
      out.write("                <p class=\"card-role\">Founder</p>\r\n");
      out.write("                <p class=\"card-email\">dhamalamanish32@gmail.com</p>\r\n");
      out.write("                <p><button class=\"button\" onclick=\"window.open( 'https://www.facebook.com/manish.dhamala.11', '_blank')\">Contact</button></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- card 5 -->\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-img\">\r\n");
      out.write("                <img\r\n");
      out.write("                        src=\"../assets/Hem.jpg\" alt=\"User 3\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-info\">\r\n");
      out.write("                <h2 class=\"card-name\">Hem Bahadur Pun</h2>\r\n");
      out.write("                <p class=\"card-role\">Founder</p>\r\n");
      out.write("                <p class=\"card-email\">hemthegentlemen@gmail.com</p>\r\n");
      out.write("                <p><button class=\"button\" onclick=\"window.open(  'https://www.facebook.com/heemal.himalpun', '_blank')\">Contact</button></p>\r\n");
      out.write("            </div>");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
