/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-04-21 05:24:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.icp.gadgets.model.User;
import java.util.ArrayList;
import com.icp.gadgets.model.Cart;
import java.util.List;
import com.icp.gadgets.doa.ProductDoa;
import com.icp.gadgets.model.Product;
import com.icp.gadgets.doa.ImageDoa;

public final class CartPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("com.icp.gadgets.model.Cart");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.icp.gadgets.model.Product");
    _jspx_imports_classes.add("com.icp.gadgets.doa.ProductDoa");
    _jspx_imports_classes.add("com.icp.gadgets.model.User");
    _jspx_imports_classes.add("com.icp.gadgets.doa.ImageDoa");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Cart</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../styles/global.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../styles/css/myToast.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

    User user = (User) session.getAttribute("user");


    ArrayList<Cart>  cart_list = (ArrayList<Cart>) session.getAttribute("cart-list");
    List<Cart> cartProduct = null;
    if (cart_list != null) {
        ProductDoa pDao = new ProductDoa();
        cartProduct =   pDao.getCartProducts(cart_list);
        request.setAttribute("cart_List", cart_list);
        double total = pDao.getTotalCartPrice(cart_list);
        request.setAttribute("total", total);
    }
    ProductDoa pd = new ProductDoa();
    List<Product> productList = pd.getAllProducts();

    ImageDoa img = new ImageDoa();


      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"h-100 h-custom\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container py-5 h-100\">\r\n");
      out.write("        <div class=\"row d-flex justify-content-center align-items-center h-100\">\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-body p-4\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-7\">\r\n");
      out.write("                                <h5 class=\"mb-3\"><a href=\"./shop.jsp\" class=\"text-body\">\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 448 512\" height=\"16\"\r\n");
      out.write("                                         width=\"16\">\r\n");
      out.write("                                        <path d=\"M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z\"></path>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    Continue shopping</a></h5>\r\n");
      out.write("                                <hr>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <p class=\"mb-1\">Shopping cart</p>\r\n");
      out.write("                                        <p class=\"mb-0\">You have ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart_List.size()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" items in your cart</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");

                                    if (cart_list != null) {
                                        for (Cart cart : cartProduct) {
                                
      out.write("\r\n");
      out.write("                                <div class=\"card mb-3\">\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                                            <div class=\"d-flex flex-row align-items-center\">\r\n");
      out.write("                                                <div>\r\n");
      out.write("                                                    <img src=\"");
      out.print( img.getImgURLByProductId(cart.getProductId()) );
      out.write("\" class=\"img-fluid rounded-3\" alt=\"Shopping item\" style=\"width: 65px;\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"ms-3\">\r\n");
      out.write("                                                    <h5>");
      out.print( cart.getProductName());
      out.write("</h5>\r\n");
      out.write("                                                    <p class=\"small mb-0\">");
      out.print( cart.getProductDescription());
      out.write("</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"d-flex flex-row align-items-center\">\r\n");
      out.write("                                                <div style=\"width: 50px;\">\r\n");
      out.write("                                                    <h5 class=\"fw-normal mb-0\">");
      out.print( cart.getQuantity());
      out.write("</h5>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div style=\"width: 80px;\">\r\n");
      out.write("                                                    <h5 class=\"mb-0\">");
      out.print( cart.getProductPrice() );
      out.write("</h5>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <a href=\"../RemoveFromCart-servlet?id=");
      out.print(cart.getProductId() );
      out.write("\" style=\"color: #cecece;\">\r\n");
      out.write("                                                    <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 448 512\" height=\"16\" width=\"16\">\r\n");
      out.write("                                                        <path d=\"M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z\"/>\r\n");
      out.write("                                                    </svg>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");

                                        }
                                    }
                                
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-5\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"card text-white rounded-3\" style=\"background: orange\">\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("                                            <h5 class=\"mb-0\">Card details</h5>\r\n");
      out.write("                                            <img src=\"https://mdbcdn.b-cdn.net/img/Photos/Avatars/avatar-6.webp\"\r\n");
      out.write("                                                 class=\"img-fluid rounded-3\" style=\"width: 45px;\" alt=\"Avatar\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <p class=\"small mb-2\">Card type</p>\r\n");
      out.write("                                        <a href=\"#!\" type=\"submit\" class=\"text-white\"><i\r\n");
      out.write("                                                class=\"fab fa-cc-mastercard fa-2x me-2\"></i></a>\r\n");
      out.write("                                        <a href=\"#!\" type=\"submit\" class=\"text-white\"><i\r\n");
      out.write("                                                class=\"fab fa-cc-visa fa-2x me-2\"></i></a>\r\n");
      out.write("                                        <a href=\"#!\" type=\"submit\" class=\"text-white\"><i\r\n");
      out.write("                                                class=\"fab fa-cc-amex fa-2x me-2\"></i></a>\r\n");
      out.write("                                        <a href=\"#!\" type=\"submit\" class=\"text-white\"><i\r\n");
      out.write("                                                class=\"fab fa-cc-paypal fa-2x\"></i></a>\r\n");
      out.write("\r\n");
      out.write("                                        <form class=\"mt-4\">\r\n");
      out.write("                                            <div class=\"form-outline form-white mb-4\">\r\n");
      out.write("                                                <input type=\"text\" id=\"typeName\" class=\"form-control form-control-lg\" size=\"17\"\r\n");
      out.write("                                                       placeholder=\"Cardholder's Name\" value=\"");
      out.print( user.getFullName() );
      out.write("\"/>\r\n");
      out.write("                                                <label class=\"form-label\" for=\"typeName\" readonly=\"\">Cardholder's Name</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"form-outline form-white mb-4\">\r\n");
      out.write("                                                <input type=\"text\"  class=\"form-control form-control-lg\"\r\n");
      out.write("                                                       siez=\"17\"\r\n");
      out.write("                                                       placeholder=\"1234 5678 9012 3457\" minlength=\"19\" maxlength=\"19\"/>\r\n");
      out.write("                                                <label class=\"form-label\" for=\"typeText\">Card Number</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"row mb-4\">\r\n");
      out.write("                                                <div class=\"col-md-6\">\r\n");
      out.write("                                                    <div class=\"form-outline form-white\">\r\n");
      out.write("                                                        <input type=\"text\" id=\"typeExp\"\r\n");
      out.write("                                                               class=\"form-control form-control-lg\"\r\n");
      out.write("                                                               placeholder=\"MM/YYYY\" size=\"7\" id=\"exp\" minlength=\"7\"\r\n");
      out.write("                                                               maxlength=\"7\"/>\r\n");
      out.write("                                                        <label class=\"form-label\" for=\"typeExp\">Expiration</label>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-md-6\">\r\n");
      out.write("                                                    <div class=\"form-outline form-white\">\r\n");
      out.write("                                                        <input type=\"password\" id=\"typeText\"\r\n");
      out.write("                                                               class=\"form-control form-control-lg\"\r\n");
      out.write("                                                               placeholder=\"&#9679;&#9679;&#9679;\" size=\"1\"\r\n");
      out.write("                                                               minlength=\"3\" maxlength=\"3\"/>\r\n");
      out.write("                                                        <label class=\"form-label\" for=\"typeText\">Cvv</label>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                        </form>\r\n");
      out.write("\r\n");
      out.write("                                        <hr class=\"my-4\">\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                                            <p class=\"mb-2\">Subtotal</p>\r\n");
      out.write("                                            <p class=\"mb-2\">NPR ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${total}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                                            <p class=\"mb-2\">Tax</p>\r\n");
      out.write("                                            <p class=\"mb-2\">13%</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                                            <p class=\"mb-2\">Shipping</p>\r\n");
      out.write("                                            <p class=\"mb-2\">NPR 1500</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"d-flex justify-content-between mb-4\">\r\n");
      out.write("                                            <p class=\"mb-2\">Total</p>\r\n");
      out.write("                                            <p class=\"mb-2\">NPR ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(total + 13/100 * total)+1500}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        <button type=\"button\" class=\"btn btn-info btn-block btn-lg\"\r\n");
      out.write("                                                style=\"background: #1a1d20; color: whitesmoke; width: 100% \" >\r\n");
      out.write("                                            <div class=\" \" style=\"text-align: center\">\r\n");
      out.write("                                                <span>Checkout <svg xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                                                                    viewBox=\"0 0 448 512\" width=\"16\" height=\"16\" fill=\"white\"><path\r\n");
      out.write("                                                        d=\"M438.6 278.6c12.5-12.5 12.5-32.8 0-45.3l-160-160c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L338.8 224 32 224c-17.7 0-32 14.3-32 32s14.3 32 32 32l306.7 0L233.4 393.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l160-160z\"/></svg></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </button>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
