/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-04-21 06:21:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.icp.gadgets.utils.StringUtils;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("com.icp.gadgets.utils.StringUtils");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Register</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/styles/css/register.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"title\">Registration</div>\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");

            String errorMessage = (String) request.getParameter(StringUtils.ERROR_MESSAGE);

            if (errorMessage != null && !errorMessage.isEmpty()) {
        
      out.write("\r\n");
      out.write("            <div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("                <i class=\"fa-solid fa-circle-xmark\"  style=\"color: #ff0000; font-size: 2em; padding-left: 15px;\"></i>\r\n");
      out.write("                <span style=\"padding-left: 5px; color: #ff0000;\">");
      out.print(errorMessage);
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("        <form action=\"");
      out.print(request.getContextPath());
      out.write("/register-servlet\"  method=\"post\">\r\n");
      out.write("            <div class=\"user-details\">\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"details\">Full Name</span>\r\n");
      out.write("                    <input type=\"text\" name=\"fullname\" placeholder=\"Enter your full name\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"details\">Username</span>\r\n");
      out.write("                    <input type=\"text\" name=\"username\" placeholder=\"Enter your username\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"details\">Email</span>\r\n");
      out.write("                    <input type=\"text\" name=\"email\" placeholder=\"Enter your email\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"details\">Phone Number</span>\r\n");
      out.write("                    <input type=\"text\" name=\"phonenumber\" placeholder=\"Enter your number\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"details\">Address</span>\r\n");
      out.write("                    <input type=\"text\" name=\"address\" placeholder=\"Enter your addreess\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"details\">Date of Birth</span>\r\n");
      out.write("                    <input type=\"date\" name=\"dob\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"details\">Password</span>\r\n");
      out.write("                    <input type=\"password\" name=\"password\" placeholder=\"Enter your password\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"gender-details\">\r\n");
      out.write("                <input type=\"radio\" name=\"gender\" id=\"dot-1\" value=\"MALE\" required>\r\n");
      out.write("                <input type=\"radio\" name=\"gender\" id=\"dot-2\" value=\"FEMALE\" required>\r\n");
      out.write("                <input type=\"radio\" name=\"gender\" id=\"dot-3\" value=\"OTHER\" required>\r\n");
      out.write("                <span class=\"gender-title\">Gender</span>\r\n");
      out.write("                <div class=\"category\">\r\n");
      out.write("                    <label for=\"dot-1\">\r\n");
      out.write("                        <span class=\"dot one\"></span>\r\n");
      out.write("                        <span class=\"gender\">Male</span>\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <label for=\"dot-2\">\r\n");
      out.write("                        <span class=\"dot two\"></span>\r\n");
      out.write("                        <span class=\"gender\">Female</span>\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <label for=\"dot-3\">\r\n");
      out.write("                        <span class=\"dot three\"></span>\r\n");
      out.write("                        <span class=\"gender\">Other</span>\r\n");
      out.write("                    </label>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"button\">\r\n");
      out.write("                <input type=\"submit\" value=\"Register\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"signup-link\">\r\n");
      out.write("                Already a member? <a href=\"login.jsp\">Login now</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
